import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav>
            <Link href="/" title="home page">Home</Link>&nbsp;|&nbsp;
            <Link href="/about" title="about page">About</Link>&nbsp;|&nbsp;
            <Link href="/posts/1">Post 1</Link>&nbsp;|&nbsp;
            <Link href="/posts/2">Post 2</Link>&nbsp;|&nbsp;
            <Link href="/posts/3">Post 3</Link>
          </nav>
        </header>

        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
