// import Link from "next/link";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Gelasio } from "next/font/google";
import Header from "@/components/Header";
// import headerStyles from "./header.module.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gel = Gelasio({
  variable: "--font-gelasio",
  style: "italic",
  subsets: ["latin"],
  weight: "500",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gel.className}>
        <Header />
        {/* <Header /> */}
        {/* <header>
          <nav>
            <Link href="/" title="home page">Home</Link>&nbsp;|&nbsp;
            <Link href="/about" title="about page">About</Link>&nbsp;|&nbsp;
            <Link href="/posts/1">Post 1</Link>&nbsp;|&nbsp;
            <Link href="/posts/2">Post 2</Link>&nbsp;|&nbsp;
            <Link href="/posts/3">Post 3</Link>
          </nav>
        </header> */}

        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}

// Q. is it a requirement to have a font in next.js layout.js
// A.
// No, it is
// not a strict technical requirement to define a custom font in your Next.js root layout (layout.js or layout.tsx). If you do not define a font, your application will fall back to the browser's default system fonts (usually Times New Roman or Arial). 
// However, implementing a font in the root layout is highly recommended for performance and design consistency. 
// Here is a breakdown of the rules and best practices:
// 1. The Root Layout is Required, Fonts Are Not 
// While the app/layout.tsx file itself is required in the App Router to define the <html> and <body> tags, you are not obligated to import next/font. 
// 2. Why You Should Put Fonts in the Layout
// If you are using custom fonts or Google Fonts, placing them in the Root Layout (app/layout.tsx) is the best practice for several reasons:

//     Performance & SEO: next/font automatically optimizes fonts and downloads them at build time, preventing layout shifts (CLS) and speeding up loading.
//     Global Application: Defining a font in the root layout applies it to your entire application.
//     Prevent Duplicate Requests: It ensures the font is loaded once, rather than loading multiple instances on different pages. 

// 3. How to Properly Implement Fonts (App Router)
// If you choose to add a custom font, it should be done in the root layout by applying the font's class name to the <body> tag: 
// tsx

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

// Summary

//     Requirement: No, not for functionality.
//     Recommendation: Yes, use next/font in the Root Layout for performance, SEO, and visual consistency. 
